version: '3.8'

services:
  app1:
    build: ./app1
    container_name: app1
    expose:
      - 80

  app2:
    build: ./app2
    container_name: app2
    expose:
      - 80

  app3:
    build: ./app3
    container_name: app3
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
